# Generated by Django 3.2.23 on 2025-09-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=45)),
                ('l_name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('skill', models.CharField(max_length=500)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=500)),
                ('phone_no', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=45)),
                ('photo', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
