# Generated by Django 3.2.23 on 2025-09-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
